name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: alpine-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        
    - name: add
      run: sudo apk add --update alpine-sdk linux-headers git zlib-dev openssl-dev gperf cmake
    - name: mkdir build
      run: mkdir build
    - name: configure
      run: cd build && cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=.. ..
    - name: make
      run: cd build && cmake --build . --target install
